In [1]:
import pandas as pd
df = pd.read_csv("data/results.csv")
df2 = pd.read_csv("data/shootouts.csv")

In [2]:
df.head(10)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False
5,1876-03-25,Scotland,Wales,4.0,0.0,Friendly,Glasgow,Scotland,False
6,1877-03-03,England,Scotland,1.0,3.0,Friendly,London,England,False
7,1877-03-05,Wales,Scotland,0.0,2.0,Friendly,Wrexham,Wales,False
8,1878-03-02,Scotland,England,7.0,2.0,Friendly,Glasgow,Scotland,False
9,1878-03-23,Scotland,Wales,9.0,0.0,Friendly,Glasgow,Scotland,False

In [3]:
print(df.shape)
print(df.columns)

(49287, 9)
Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='str')

In [4]:
df.isnull().sum()

date           0
home_team      0
away_team      0
home_score    72
away_score    72
tournament     0
city           0
country        0
neutral        0
dtype: int64

In [5]:
print(df['date'].min())
print(df['date'].max())

1872-11-30
2026-06-27

In [6]:
wc = df[df['tournament'] == 'FIFA World Cup']
wc.head(10)
wc.head(-10)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
1486,1930-07-13,Belgium,United States,0.0,3.0,FIFA World Cup,Montevideo,Uruguay,True
1487,1930-07-13,France,Mexico,4.0,1.0,FIFA World Cup,Montevideo,Uruguay,True
1488,1930-07-14,Brazil,Yugoslavia,1.0,2.0,FIFA World Cup,Montevideo,Uruguay,True
1489,1930-07-14,Peru,Romania,1.0,3.0,FIFA World Cup,Montevideo,Uruguay,True
1490,1930-07-15,Argentina,France,1.0,0.0,FIFA World Cup,Montevideo,Uruguay,True
...,...,...,...,...,...,...,...,...,...
49272,2026-06-25,Ecuador,Germany,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49273,2026-06-25,Japan,Sweden,NaN,NaN,FIFA World Cup,Arlington,United States,True
49274,2026-06-25,Tunisia,Netherlands,NaN,NaN,FIFA World Cup,Kansas City,United States,True
49275,2026-06-26,Egypt,Iran,NaN,NaN,FIFA World Cup,Seattle,United States,True
49276,2026-06-26,New Zealand,Belgium,NaN,NaN,FIFA World Cup,Vancouver,Canada,True

In [7]:
valid_rows = df2.iloc[:, 4].notna()

same_count = (df2.loc[valid_rows].iloc[:, 3] ==
              df2.loc[valid_rows].iloc[:, 4]).sum()

total_valid = valid_rows.sum()

percentage = 100 * same_count / total_valid

print(f"Percentage: {percentage:.2f}%")

Percentage: 53.66%

In [8]:
import pandas as pd
from model.poisson_model import load_fifa_points, FIFA_NAME_MAP
from model.data_prep import load_and_prepare

df = load_and_prepare("data/results.csv")
results_teams = set(pd.unique(df[['home_team','away_team']].values.ravel()))
fifa_pts = load_fifa_points("data/fifa_mens_rank.csv")

unmatched = results_teams - set(fifa_pts.keys())
print(f"{len(unmatched)} teams in results with no FIFA match:")
for t in sorted(unmatched): print(" ", t)

119 teams in results with no FIFA match:
  Abkhazia
  Alderney
  Ambazonia
  Andalusia
  Arameans Suryoye
  Artsakh
  Aymara
  Barawa
  Basque Country
  Biafra
  Bonaire
  Bosnia and Herzegovina
  Brittany
  Brunei
  Canary Islands
  Cascadia
  Catalonia
  Chagos Islands
  Chameria
  Chechnya
  China PR
  Cilento
  Congo
  Corsica
  County of Nice
  Crimea
  Darfur
  Donetsk PR
  Délvidék
  Elba Island
  Ellan Vannin
  Eswatini
  Falkland Islands
  Felvidék
  Franconia
  French Guiana
  Frøya
  Galicia
  Gotland
  Gozo
  Greenland
  Guadeloupe
  Guernsey
  Găgăuzia
  Hitra
  Hmong
  Iraqi Kurdistan
  Isle of Man
  Isle of Wight
  Jersey
  Kabylia
  Kernow
  Kiribati
  Kyrgyzstan
  Kárpátalja
  Luhansk PR
  Madrid
  Mapuche
  Marshall Islands
  Martinique
  Matabeleland
  Maule Sur
  Mayotte
  Menorca
  Micronesia
  Monaco
  North Macedonia
  Northern Cyprus
  Northern Mariana Islands
  Occitania
  Orkney
  Padania
  Palau
  Panjab
  Parishes of Jersey
  Provence
  Raetia
  Republic of St. Pauli
  Rhodes
  Romani people
  Ryūkyū
  Réunion
  Saare County
  Saint Barthélemy
  Saint Helena
  Saint Martin
  Saint Pierre and Miquelon
  Sark
  Saugeais
  Sealand
  Seborga
  Shetland
  Silesia
  Sint Maarten
  Somaliland
  South Ossetia
  Surrey
  Székely Land
  Sápmi
  Taiwan
  Tamil Eelam
  Tibet
  Ticino
  Trinidad and Tobago
  Tuvalu
  Two Sicilies
  United Koreans in Japan
  United States Virgin Islands
  Vatican City
  Wallis Islands and Futuna
  West Papua
  Western Armenia
  Western Isles
  Western Sahara
  Ynys Môn
  Yorkshire
  Yoruba Nation
  Zanzibar
  Åland Islands